germainDb:
  Hostname: "germain-db.crs7ftpnebbj.us-west-2.rds.amazonaws.com"
  Port: "3306"
  Sid: "orclpdb" #Only applicable for Oracle
  clusterServiceName: "germainapm-db"

germainDbBootstrap:
  Username: "germain"
  Password: "germain-db"

germainConfig:
  DbType: "MYSQL" #MYSQL/ORACLE
  Username: "APMCFG"
  Password: "APMCFG"

germainDatamart:
  DbType: "MYSQL" #MYSQL/ORACLE/ELASTIC
  Username: "APMDAT"
  Password: "APMDAT"

germainIndexer:
  name: "ELASTIC_SEARCH" #NOOP/SOLR/ELASTIC_SEARCH
  Url: "http://germainapm-elasticsearch:9200"
  Username: ""
  Password: ""

germainMail:
  From: "noreply@germainuxlocal.com"
  Host: "localhost"
  Username: "admin"
  Password: "admin"
  Port: "587"

spec:
  elasticSearch:
    name: "elasticsearch"
    tag: "8.8.1"
    pullPolicy: Always
    replicas: 2
    serviceName: "germainapm-elasticsearch"
    cpuRequest: 100m
    cpuLimit: 1000m
    memoryRequest: 1024Mi
    memoryLimit: 4096Mi
    minReadySeconds: 10
    volumeClaim: 10Gi
  kibana:
    name: "kibana"
    tag: "8.8.1"
    pullPolicy: Always
    replicas: 1
    serviceName: "germainapm-kibana"
    cpuRequest: 100m
    cpuLimit: 1000m
    memoryRequest: 512Mi
    memoryLimit: 2048Mi
    minReadySeconds: 10
  activeMQ:
    name: "rmohr/activemq"
    tag: "latest"
    pullPolicy: Always
    replicas: 1
    serviceName: "germainapm-activemq"
    cpuRequest: 100m
    cpuLimit: 1000m
    memoryRequest: 256Mi
    memoryLimit: 1024Mi
    minReadySeconds: 10
  zookeeper:
    name: "zookeeper"
    tag: "latest"
    pullPolicy: Always
    replicas: 2
    serviceName: "germainapm-zookeeper"
    cpuRequest: 100m
    cpuLimit: 1000m
    memoryRequest: 256Mi
    memoryLimit: 1024Mi
    minReadySeconds: 10
    volumeClaim: 1Gi
  hazelcast:
    name: "hazelcast/hazelcast"
    tag: "5.2.2-SNAPSHOT"
    pullPolicy: Always
    replicas: 1
    serviceName: "germainapm-hazelcast"
    cpuRequest: 100m
    cpuLimit: 1000m
    memoryRequest: 512Mi
    memoryLimit: 2048Mi
    minReadySeconds: 10
  germainServer:
    name: "public.ecr.aws/h0m9e4y5/germainapm-server"
    tag: "2023.2"
    pullPolicy: Always
    replicas: 2
    serviceName: "germainapm-server"
    cpuRequest: 100m
    cpuLimit: 1000m
    memoryRequest: 1024Mi
    memoryLimit: 4096Mi
    minReadySeconds: 10
  germainStorage:
    name: "public.ecr.aws/h0m9e4y5/germainapm-services"
    tag: "2023.2"
    pullPolicy: Always
    replicas: 1
    serviceName: "germainapm-storage"
    cpuRequest: 100m
    cpuLimit: 1000m
    memoryRequest: 1024Mi
    memoryLimit: 4096Mi
    minReadySeconds: 10
  germainSession:
    name: "public.ecr.aws/h0m9e4y5/germainapm-services"
    tag: "2023.2"
    pullPolicy: Always
    replicas: 1
    serviceName: "germainapm-session"
    cpuRequest: 100m
    cpuLimit: 1000m
    memoryRequest: 512Mi
    memoryLimit: 2048Mi
    minReadySeconds: 10
  germainAnalytics:
    name: "public.ecr.aws/h0m9e4y5/germainapm-services"
    tag: "2023.2"
    pullPolicy: Always
    replicas: 1
    serviceName: "germainapm-analytics"
    cpuRequest: 100m
    cpuLimit: 1000m
    memoryRequest: 512Mi
    memoryLimit: 2048Mi
    minReadySeconds: 10
  germainAggregation:
    name: "public.ecr.aws/h0m9e4y5/germainapm-services"
    tag: "2023.2"
    pullPolicy: Always
    replicas: 1
    serviceName: "germainapm-aggregation"
    cpuRequest: 100m
    cpuLimit: 1000m
    memoryRequest: 512Mi
    memoryLimit: 2048Mi
    minReadySeconds: 10
  germainAction:
    name: "public.ecr.aws/h0m9e4y5/germainapm-services"
    tag: "2023.2"
    pullPolicy: Always
    replicas: 1
    serviceName: "germainapm-action"
    cpuRequest: 100m
    cpuLimit: 1000m
    memoryRequest: 512Mi
    memoryLimit: 2048Mi
    minReadySeconds: 10
  germainRtm:
    name: "public.ecr.aws/h0m9e4y5/germainapm-services"
    tag: "2023.2"
    pullPolicy: Always
    replicas: 1
    serviceName: "germainapm-rtm"
    cpuRequest: 100m
    cpuLimit: 1000m
    memoryRequest: 512Mi
    memoryLimit: 2048Mi
    minReadySeconds: 10

storageClass:
  name: "ebs-sc"
  fstype: "ext4"
  type: "gp3"
  iops: "3000"

livenessProbe:
  initialDelaySeconds: 900
  periodSeconds: 10
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 20

readinessProbe:
  initialDelaySeconds: 60
  periodSeconds: 10
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 3

activeMQXml: "config/activemq.xml"
activeMQEnv: "config/activemq.env"
startZookeeper: "config/start-zookeeper"
zookeeperReady: "config/zookeeper-ready"
commonProperties: "config/common.properties"
licenseFolder: "config/license/*"
rtmVersions: ["2022.5", "2023.1"]

ServiceCheck:
  zookeeper: while [[ \"$(echo ruok | nc germainapm-zookeeper 2181; echo)\" != \"imok\" ]]; do sleep 5; done;
  activemq: while [[ \"$(wget --server-response http://germainapm-activemq:8161 2>&1 | awk '/^  HTTP/{print $2}')\" != \"200\" ]]; do sleep 10; done;
  elastic: while [[ \"$(wget --server-response http://germainapm-elasticsearch:9200 2>&1 | awk '/^  HTTP/{print $2}')\" != \"200\" ]]; do sleep 10; done;
  db: while [[ \"$(nc -z -v -w3 http://germainapm-db 3306 | grep -o open 2>&1)\" != \"open\" ]]; do sleep 10; done;
  storage: while [[ \"$(wget --server-response http://germainapm-storage:8080/actuator/prometheus 2>&1 | awk '/^  HTTP/{print $2}')\" != \"200\" ]]; do sleep 10; done;
