weight: 4

---
apiVersion: v1
kind: Service
metadata:
  name: germainapm-kibana
spec:
  type: LoadBalancer
  selector:
    app: kibana
  ports:
    - name: germainapm-kibana-port
      port: 5601
      protocol: TCP
      targetPort: kibana-port

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
spec:
  replicas: {{ .Values.replicas.kibana }}
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
        - image: {{ .Values.image.kibana }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: kibana
          resources:
            requests:
              memory: {{ .Values.resources.requests.memory.kibana }}
              cpu: {{ .Values.resources.requests.cpu.kibana }}
            limits:
              memory: {{ .Values.resources.limits.memory.kibana }}
              cpu: {{ .Values.resources.limits.cpu.kibana }}
          ports:
            - containerPort: 5601
              name: kibana-port
              protocol: TCP
          env:
          - name: ELASTICSEARCH_HOSTS
            value: "http://germainapm-elasticsearch:9200"
          - name: XPACK_SECURITY_ENABLED
            value: "false"