apiVersion: v1
kind: Pod
metadata:
  name: log-monitor
spec:
  containers:
  - image: busybox
    name: log-monitor
    resources:
      requests:
        memory: 512Mi
        cpu: 100m
      limits:
        memory: 512Mi
        cpu: 1000m
    command: ["tail"]
    args: ["-f", "/dev/null"]
    volumeMounts:
    - mountPath: /esdata-elastic-1
      name: esdata-elastic-1
  volumes:
  - name: esdata-elastic-1
    persistentVolumeClaim:
      claimName: esdata-elastic-1
      readOnly: true