---
apiVersion: v1
kind: Service
metadata:
  name: germainapm-hazelcast
spec:
  clusterIP: None
  selector:
    app: hazelcast
  ports:
    - name: germainapm-hazelcast-port
      port: 5701
      protocol: TCP
      targetPort: hazelcast-port
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hazelcast
spec:
  replicas: {{ .Values.replicas.hazelcast }}
  selector:
    matchLabels:
      app: hazelcast
  template:
    metadata:
      labels:
        app: hazelcast
    spec:
      containers:
        - image: {{ .Values.image.hazelcast }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: hazelcast
          resources:
            requests:
              memory: {{ .Values.resources.requests.memory.hazelcast }}
              cpu: {{ .Values.resources.requests.cpu.hazelcast }}
            limits:
              memory: {{ .Values.resources.limits.memory.hazelcast }}
              cpu: {{ .Values.resources.limits.cpu.hazelcast }}
          ports:
            - containerPort: 5701
              name: hazelcast-port
          env:
            - name: HZ_CLUSTERNAME
              value: "germain"